all:
	make -f fcrypt.mak all
	make -f fdecrypt.mak all
	make -f fcrypt_auth_db.mak all

install:
	make -f fcrypt.mak install
	make -f fdecrypt.mak install
	make -f fcrypt_auth_db.mak install

clean:
	make -f fcrypt.mak clean
	make -f fdecrypt.mak clean
	make -f fcrypt_auth_db.mak clean
