all:
	nmake -f fcrypt.vc all
	nmake -f fdecrypt.vc all

install:
	copy fcrypt.exe ..\bin\fcrypt.exe
	copy fdecrypt.exe ..\bin\fdecrypt.exe

clean:
	nmake -f fcrypt.vc clean
	nmake -f fdecrypt.vc clean
