all:
	make -f aesdb_single_file_buffer_crypt_test.mak all
	make -f aesdb_whole_file_crypt_test.mak all
	make -f aesdb_file_encrypt.mak all
	make -f aesdb_file_decrypt.mak all
	make -f rsadb_single_file_buffer_crypt_test.mak all
	make -f smartcard_encrypt_test.mak all

install:
	make -f aesdb_single_file_buffer_crypt_test.mak instal
	make -f aesdb_whole_file_crypt_test.mak install
	make -f aesdb_file_encrypt.mak install
	make -f aesdb_file_decrypt.mak install
	make -f rsadb_single_file_buffer_crypt_test.mak install
	make -f smartcard_encrypt_test.mak install

clean:
	make -f aesdb_single_file_buffer_crypt_test.mak clean
	make -f aesdb_whole_file_crypt_test.mak clean
	make -f aesdb_file_encrypt.mak clean
	make -f aesdb_file_decrypt.mak clean
	make -f rsadb_single_file_buffer_crypt_test.mak clean
	make -f smartcard_encrypt_test.mak clean

